==========================================
SLURM_JOB_ID = 6440
SLURM_NODELIST = virya2
==========================================
Wed Dec 20 14:24:47 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-PCIE-32GB           Off | 00000000:49:00.0 Off |                    0 |
| N/A   26C    P0              23W / 250W |      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
2023-12-22 21:35:26,682 - INFO - Available device: cuda:0
Traceback (most recent call last):
  File "/home/h_ghazik/plm_secondary_integration/localization_attention.py", line 126, in <module>
    fire.Fire(main)
  File "/home/h_ghazik/.conda/envs/py39/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/h_ghazik/.conda/envs/py39/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/h_ghazik/.conda/envs/py39/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/h_ghazik/plm_secondary_integration/localization_attention.py", line 77, in main
    dataset = load_dataset("proteinea/deeploc")
  File "/home/h_ghazik/.conda/envs/py39/lib/python3.9/site-packages/datasets/load.py", line 2129, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/h_ghazik/.conda/envs/py39/lib/python3.9/site-packages/datasets/load.py", line 1815, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/h_ghazik/.conda/envs/py39/lib/python3.9/site-packages/datasets/load.py", line 1512, in dataset_module_factory
    raise e1 from None
  File "/home/h_ghazik/.conda/envs/py39/lib/python3.9/site-packages/datasets/load.py", line 1468, in dataset_module_factory
    raise ConnectionError(f"Couldn't reach '{path}' on the Hub ({type(e).__name__})")
ConnectionError: Couldn't reach 'proteinea/deeploc' on the Hub (SSLError)
